### PR TITLE
New syntax

### PR DESCRIPTION
**Pull request by williambl**
This branch has accomplished its goal of getting the new syntax to work, so I say we merge it.

### CODE REVIEW

**Comment by Valiec** [comment]
I was taking a look at this, and it should *not* be merged yet. It produces an UnboundLocalError when you try to install a Forge mod. I've fixed it on my local copy, but I'm also working on elimination unwanted console output (e.g. "Enter mod folder location for instance default (absolute path):  **Mod folder for default path DeltaMC**", especially the bold part) when creating an instance.

**Comment by williambl** [comment]
Alright. I agree.

**Comment by Valiec** [comment]
I pushed the UnboundLocalError fix.

**Comment by williambl** [comment]
Okay, now that those problems are fixed, would you say it's mergeable?

**Comment by Valiec** [comment]
I think it's ready to merge.

**Comment by williambl** [comment]
Okay, I'm merging this and deltamc-archive/#9 at the same time.

**Pull request merged**
